apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ol986chz3-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ol986chz3-java-springboot-gitops